config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :manages
  
  
  resources :manages do
    resources :pictures, :only => [:create, :destroy] # support #create and #destroy
   
   
  end
  
   root 'menucliente#home'
   get "pedidosf" => "manages#pedidosf"
   get "solicitacoes" => "manages#solicitacoes"
   
   
  resources :menucliente do
    member do
      get "pratos"
      get "show"
      get "lista"
      post "lista"
      post "list"
      post "chama_garcom2"
      get "limplista"
      delete "del"=> "menucliente#destroy"
      post "pedid_save"
      delete "apagarpedido"=> "menucliente#apaga_ped"
      delete "apagarpedidof" => "menucliente#apaga_ped_f" 
      delete "apagarsolicitacoes" => "manages#sdestroy"
      get "atendersolic" => "manages#atendersolic"
    end
    
    collection do
      get "home"
      get "cardapio"
      get "pratos"
      get "show"
      get "lista"
      get "pedidos"
      post "pedidos"
      get "conta"
      get "pratoscar"
      post "chama_garcom"
      get "chama_garcom"
      get "chama_garcom2"
      get "chama_garcom3"
      get "selecmesa"
      post "select_mesa"
      
    end
  end
  
   

end

app/controllers/menucliente_controller.rb
class MenuclienteController < ApplicationController
    
    before_action :procprat, only: [:pratos, :pratoscar]
    before_action :mesa_escolhida
    $seq_ped = 0
    
    def select_mesa
        @mesa_esc = MesasTemp.new
        @mesa_esc.mesa = params[:mesa]
        
        if @mesa_esc.mesa == ""
            respond_to do |format|
                format.html { redirect_to selecmesa_menucliente_index_path, notice: 'Escolha uma mesa para continuar.' }
                format.json { head :no_content }
            end

        else
            if @mesa_esc.save
                respond_to do |format|
                    format.html { redirect_to cardapio_menucliente_index_path, notice: 'Mesa escolhida com sucesso.' }
                    format.json { head :no_content }
                end
            end
        end
    end
    
    def pratos
    end
    
    def pratoscar
       @escolha_ped = Manage.all
    end
    
    # GET /menucliente/1
    # GET /menucliente/1.json
    def show
        @mostra = Manage.find(params[:id])
    end
    
    def list
        @list_comp = List.new
        @mostra = Manage.find(params[:id])
        @list_comp.qtd = params[:qtds]
        @list_comp.total = (params[:qtds]).to_i * (@mostra.price).to_f
        @list_comp.manage_id = params[:id]
        @list_comp.namep = @mostra.name
        @list_comp.price = @mostra.price
        @list_comp.mesa_n = @mesa_name.mesa
        @list_comp.save

        redirect_to lista_menucliente_path
    end
    
    def lista
        @list_compx = List.where(mesa_n: @mesa_name.mesa)
    end
    
    def limplista
        @list_compx = List.where(mesa_n: @mesa_name.mesa)
        @list_compx.each do |x|
            x.destroy
        end
        redirect_to lista_menucliente_path
    end
    
    def destroy
        @del = List.find(params[:id])
        @del.destroy
        respond_to do |format|
            format.html { redirect_to lista_menucliente_path, notice: 'Item deletado com sucesso.' }
            format.json { head :no_content }
        end
    end
    
    def apaga_ped
        
        @del = OrderListDef.find(params[:id])
        @tempo = ((@del.created_at + 1800)-(Time.now))/60
        if @tempo > 27
            @del.destroy
            respond_to do |format|
                format.html { redirect_to pedidos_menucliente_index_path, notice: 'Pedido cancelado!' }
                format.json { head :no_content }
            end
        else
            respond_to do |format|
                format.html { redirect_to pedidos_menucliente_index_path, alert: 'O pedido não pôde ser cancelado pois já se passaram 3 minutos de sua realização. Chame o garçom para solicitar o cancelamento.' }
                format.json { head :no_content }
            end
        end
    end
    
    def apaga_ped_f
        
        @del = OrderListDef.find(params[:id])
        @del.destroy
        
        respond_to do |format|
                format.html { redirect_to pedidosf_path, notice: 'Pedido finalizado com sucesso.' }
                format.json { head :no_content }
            end
        
        #redirect_to pedidosf_path
       
    end
    
    def pedid_save
            @soma = 0
            @list_price = List.where(mesa_n: @mesa_name.mesa)
            @list_price.each do |k|
                @soma += (k.total).to_f
            end
            if @soma > 0
                @ped = Order.new
                @ped.n_order = (((Time.now)-10800).strftime("%Y%m")).to_i * 10000 + $seq_ped
                $seq_ped += 1
                @ped.n_table = @mesa_name.mesa
                @ped.price = @soma
                
                @list_price.each do |tk|
                    @List_order = OrderListDef.new
                    @List_order.namep = tk.namep
                    @List_order.qtd = tk.qtd
                    @List_order.prato_price = tk.price
                    @List_order.total = tk.total
                    @List_order.manage_id = tk.id
                    @List_order.mesa_n = @ped.n_table
                    @List_order.n_order = @ped.n_order
                    @List_order.pedido_total_price = @ped.price
                    @List_order.status = 1
                    @List_order.save
                end
                @ped.save
                @list_price.each do |k|
                    k.destroy
                end
            
                respond_to do |format|
                    format.html { redirect_to pedidos_menucliente_index_path, notice: "Pedido #{@List_order.n_order} Realizado com Sucesso!! Tempo estimado de 30 minutos" }
                    format.json { head :no_content }
                end
            else
                respond_to do |format|
                    format.html { redirect_to lista_menucliente_path, alert: 'Pedido não realizado, pois nenhum prato foi escolhido!' }
                    format.json { head :no_content }
                end
            end
    end
    
    def pedidos
        @lista_ped = OrderListDef.where(mesa_n: @mesa_name.mesa)
    end
    
    def conta
        #@lista_ped = OrderListDef.where(mesa_n: @mesa_name.mesa)
        @lista_ped = OrderListDef.find_by_sql(["SELECT * FROM order_list_defs WHERE mesa_n = ? AND status = ?", @mesa_name.mesa, 1])
        #@lista_ped = OrderListDef.find(:all, :conditions => { :mesa_n => [@mesa_name.mesa] and :status => [1] })
    end
    # codigos chamado garçom
    # 01 => Duvidas diversas
    # 02 => Cancelameto de pedidos
    # 03 => Pagamentos
    
    def chama_garcom
        @c_garcom = Chamagarcom.new
        @c_garcom.mesa_num = @mesa_name.mesa
        @c_garcom.cod_chamado = 01
        @c_garcom.status = "Pendente"
        @c_garcom.save
        respond_to do |format|
                format.html { redirect_to cardapio_menucliente_index_path, notice: 'Em breve o garçom comparecerá para ajuda-lo!' }
                format.json { head :no_content }
        end
        
    end
    
    def chama_garcom2
        @c_garcom = Chamagarcom.new
        @c_garcom.mesa_num = @mesa_name.mesa
        @c_garcom.cod_chamado = 02
        @c_garcom.status = "Pendente"
        @c_garcom.save
        
        respond_to do |format|
                format.html { redirect_to pedidos_menucliente_index_path, notice: 'Em breve o garçom comparecerá para ajuda-lo!' }
                format.json { head :no_content }
        end
        
    end
    
    def chama_garcom3
        @c_garcom = Chamagarcom.new
        @c_garcom.mesa_num = @mesa_name.mesa
        @c_garcom.cod_chamado = 03
        @c_garcom.status = "Pendente"
        @c_garcom.save
        
        respond_to do |format|
                format.html { redirect_to conta_menucliente_index_path, notice: 'Em breve o garçom comparecerá para ajuda-lo!' }
                format.json { head :no_content }
        end
        
    end
    
    private
        def mesa_escolhida
            @mesa_name = MesasTemp.last
        end
    
        def procprat
            @escolha_ped = Manage.all
        end
        
        def list_params
            params.require(:list).permit(:id, :namep, :qtd, :price, :total)
        end
        
        def chamagarcom_params
            params.require(:chamagarcoms).permit(:mesa_num, :cod_chamado, :status)
        end
    
end

app/helpers/menucliente_helper.rb
module MenuclienteHelper
end

app/views/menucliente/Cardapio.html.erb
<center>
<table>
<tr>
<td align="left"><%= render partial: "hora" %></td>
<td></td>
<td><form action="action_page.php" align="center">
  <select name="mesas">
    <option value="      ">      </option>
    <option value="Mesa 1">Mesa 1</option>
    <option value="Mesa 2">Mesa 2</option>
    <option value="Mesa 3">Mesa 3</option>
    <option value="Mesa 4">Mesa 4</option>
    <option value="Mesa 5">Mesa 5</option>
    <option value="Mesa 6">Mesa 6</option>
    <option value="Mesa 7">Mesa 7</option>
    <option value="Mesa 8">Mesa 8</option>
    <option value="Mesa 9">Mesa 9</option>
  </select>
</form></td>
</tr>
</table>
</center>
<p>
<center>
<table>
<tr>
<td align="center"><%= link_to image_tag("icon_cardapio.png", size: "80x80"), 'controller'=> "menucliente", 'action'=> "Pratos"  %>
<center><font Size="4">Cardapio</font></center></td>
<td align="center"><%= link_to image_tag("icon_pedidos.jpg", size: "80x80"), 'controller'=> "menucliente", 'action'=> "Pedidos"  %>
<center><font Size="4">Pedidos</font></center></td>
</tr>
<tr>
<td align="center"><%= link_to image_tag("icon_conta.png", size: "80x80"), 'controller'=> "menucliente", 'action'=> "Pratos"  %>
<center><font Size="4">Conta</font></center></td>
<td align="center"><%= link_to image_tag("icon_garcon.png", size: "80x80"), 'controller'=> "menucliente", 'action'=> "Pratos"  %>
<center><font Size="4">Garçom</font></center></td>
</tr>
<tr>
<td align="center"><%= link_to image_tag("icon_sair.png", size: "80x80"), 'controller'=> "menucliente", 'action'=> "Home"  %>
<center><font Size="4">Sair</font></center></td>
<td></td>
</tr>
</table>
</center>

app/views/menucliente/Pedidos.html.erb
<center>
<table>
<tr>
<td align="left"><%= render partial: "hora" %></td>
<td></td>
<td><form action="action_page.php" align="center">
  <select name="mesas">
    <option value="      ">      </option>
    <option value="Mesa 1">Mesa 1</option>
    <option value="Mesa 2">Mesa 2</option>
    <option value="Mesa 3">Mesa 3</option>
    <option value="Mesa 4">Mesa 4</option>
    <option value="Mesa 5">Mesa 5</option>
    <option value="Mesa 6">Mesa 6</option>
    <option value="Mesa 7">Mesa 7</option>
    <option value="Mesa 8">Mesa 8</option>
    <option value="Mesa 9">Mesa 9</option>
  </select>
</form></td>
</tr>
</table>
</center>
<p>
<center><h3>Pedidos</h3></center>
<p>

<table border="2" align="center">
	<tr>
		<th></th>
		<th>Código</th>
		<th>Valor</th>
		<th>Tempo Estimado</th>
	</tr>
	
	<% 0..2.times do |x| %>
	<tr>
		<td align="center"><%= check_box_tag(("ped<<#{x}").to_sym) %></td>
		<td width="120px"><%=  %></td>
		<td width="80px"><%=   %></td>
		<td width="120px"><%=  %></td>
	<% end %>
	</tr>
</table>
<p>
<body>Total dos pedidos R$<input disable=disabled></input></body>

app/views/menucliente/Pratos.html.erb
<center>
<table>
<tr>
<td align="left"><%= render partial: "hora" %></td>
<td></td>
<td><form action="action_page.php" align="center">
  <select name="mesas">
    <option value="      ">      </option>
    <option value="Mesa 1">Mesa 1</option>
    <option value="Mesa 2">Mesa 2</option>
    <option value="Mesa 3">Mesa 3</option>
    <option value="Mesa 4">Mesa 4</option>
    <option value="Mesa 5">Mesa 5</option>
    <option value="Mesa 6">Mesa 6</option>
    <option value="Mesa 7">Mesa 7</option>
    <option value="Mesa 8">Mesa 8</option>
    <option value="Mesa 9">Mesa 9</option>
  </select>
</form></td>
</tr>
</table>
</center>

<center>
<table>
<tr>
<td><body>Ordenar por:</body></td>
<td><form action="action_page.php" align="center">
  <select name="mesas">
    <option value="Padrao">Padrão</option>
    <option value="Menor Preco">Menor Preço</option>
    <option value="Maior Preco">Maior Preço</option>
    <option value="Prato de Entrada">Prato de Entrada</option>
    <option value="Prato Principal">Prato Principal</option>
    <option value="Sobremesas">Sobremesas</option>
    <option value="Bebidas">Bebidas</option>
    <option value="Prato Infantil">Prato Infantil</option>
  </select>
</form></td>
<p>
<td align="center"><%= link_to image_tag("icon_matriz1.png", size: "32x32" ), 'controller'=> "menucliente", 'action'=> "Cardapio"  %></td>
</tr>
</table>
</center>
<p>
<center><%= link_to image_tag("icon_borda.png", size: "50x300" ), 'controller'=> "menucliente", 'action'=> "Cardapio"  %>
<%= link_to image_tag("icon_matriz1.png", size: "250x300" ), 'controller'=> "menucliente", 'action'=> "Cardapio"  %>
<%= link_to image_tag("icon_borda.png", size: "50x300" ), 'controller'=> "menucliente", 'action'=> "Cardapio"  %><br/>Nome<br/>Preço</center>

app/views/menucliente/_hora.html.erb
<% agora = Time.now %>
<%= (agora-10800).strftime("%d/%m/%y  %H:%M") %>
&nbsp;<%= label_tag @mesa_name.mesa %>

app/views/menucliente/_hora1.html.erb
<% agora = Time.now %>
<%= (agora-10800).strftime("%d/%m/%y  %H:%M") %>
&nbsp;<%= text_field_tag ($mesa) %>

app/views/menucliente/cardapio.html.erb
<center>
<table>
<tr>
<td align="left"><font size="3"><%= render partial: "hora" %></font></td>
</tr>
</table>
</center>
<br>
<br>
<center>
<table>
<tr>
<td align="center"><%= link_to image_tag("icon_cardapio.png", size: "80x80"), pratoscar_menucliente_index_path  %>
<center><font Size="4">Cardapio</font></center></td>
<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td align="center"><%= link_to image_tag("icon_pedidos.jpg", size: "80x80"), pedidos_menucliente_index_path  %>
<center><font Size="4">Pedidos</font></center></td>
</tr>
<tr>
<td align="center"><%= link_to image_tag("icon_conta.png", size: "80x80"), conta_menucliente_index_path  %>
<center><font Size="4">Conta</font></center></td>
<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
<td align="center"><%= link_to image_tag("icon_garcon.png", size: "80x80"), chama_garcom_menucliente_index_path, data: { confirm: "Esta ação solicitará atendimento ao garçom por motivos gerais. Tem certeza disso?"} %>
<center><font Size="4">Garçom</font></center></td>
</tr>
<tr>
<td align="center"><%= link_to image_tag("icon_sair.png", size: "80x80"), home_menucliente_index_path  %>
<center><font Size="4">Sair</font></center></td>
<td></td>
</tr>
</table>
</center>

app/views/menucliente/conta.html.erb
<center>
<table>
    <tr>
        <td align="left"><font size="3"><%= render partial: "hora" %></font></td>
    </tr>
</table>
</center>
<br>
<br>
<center><h3>Conta</h3></center>
<p>
<center>
<div id="MainMenu" style="background-color:#00BFFF; width:400px">
  <div class="list-group panel">
      
    <% x = 0 %>
    <% @lista_ped.each do |pedido|%>
        <% if x < pedido.n_order   %>
            <a href="#<%= pedido.n_order %>" class="list-group-item list-group-item-success" data-toggle="collapse">
                    <%= "Pedido: N° %d" %pedido.n_order %> _ _ _ _ _ <%= "Total: R$ %.2f" %pedido.pedido_total_price %></a>
        <%end%>  
        <% x = pedido.n_order %>
        
        <div class="collapse" id="<%= pedido.n_order %>">
            <% @lista_ped.each do |pedix|%>
                <% if x == pedix.n_order   %>
                    <a class="list-group-item"><%= pedix.namep %> _ _ _ <%= "Quant: %02d" %pedix.qtd %> _ _ _ <%= "Preço: R$ %.2f" %pedix.total %></a>
                <%end%>
            <%end%>
        </div>
  
    </body>    
    <%end%>
  </div>
</div>
</center>

<center>
    <%= link_to button_tag('Fechar Conta'), chama_garcom3_menucliente_index_path, data: { confirm: "Esta ação solicitará a presença do garçom para o pagamento da conta. Tem certeza disso?"} %>
    <%= link_to button_tag('Voltar'), cardapio_menucliente_index_path %>
</center>

app/views/menucliente/home.html.erb
<!--<center><h2>Open Menu</h2></center>-->
<div>
    <center><%= link_to image_tag("icon_menu.jpg"), selecmesa_menucliente_index_path  %></center>
</div>

app/views/menucliente/lista.html.erb
<%= form_tag (pedid_save_menucliente_path) do %>
	
	<center>
	<table>
	<tr>
	<td align="left"><font size="3"><%= render partial: "hora" %></font></td>
	</tr>
	</table>
	</center>
	<br>
	<center><h3>Lista de Compra</h3></center>
	<p>
	
	<table border="2" align="center">
		<tr>
			<th width="150px"><center>Item</center></th>
			<th width="80px"><center>Qtd</center></th>
			<th width="120px"><center>Preço</center></th>
			<th width="120px"><center>Total</center></th>
		</tr>
		<% total = 0 %>
		<% @list_compx.each do |y|%>
		<tr>
			<td align="center"><%= y.namep %></td>
			<td align="center"><%= "%02d" %y.qtd %></td>
			<td align="center"><%= "R$ %.2f" %y.price %></td>
			<td align="center"><%= "R$ %.2f" %y.total %></td>
			<td><%= link_to ("X"),
                      del_menucliente_path(y), 
                      :method => :delete,
                      :data => { :confirm => ('Deseja realmente deletar?')},
                      :class => 'btn btn-xs btn-danger' %>
			<% total += (y.total).to_f %></td>
		</tr>
		<% end %>
	</table>
	<p>
	<p>
	
	<center><body>Total dos pedidos <%= label_tag("R$ %.2f" %total) %></body></center>
	<p>
	<p>
	
	<center><body>	
	<%= submit_tag "Finalizar Pedido", :data => { :confirm => ('Deseja finalizar o pedido?')} %>
<% end %>
<%= link_to button_tag('Limpar Lista'), limplista_menucliente_path %>
<%= link_to button_tag('Voltar ao Cardapio'), pratoscar_menucliente_index_path %></body></center>

app/views/menucliente/pedidos.html.erb
	<center>
	<table>
	<tr>
	<td align="left"><font size="3"><%= render partial: "hora" %></font></td>
	</tr>
	</table>
	</center>
	<br>
	<center><h3>Pedidos</h3></center>
	<p>
	
	<table border="2" align="center">
		<tr>
			<th width="120px"><center>N° do pedido</center></th>
			<th width="120px"><center>Valor</center></th>
			<th width="120px"><center>Tempo Estimado</center></th>
		</tr>
		<% @total = 0 %>
		<% @lista_ped.each do |x| %>
		
		<tr>
			<td align="center"><%= x.n_order %></td>
			<td align="center"><%= "R$ %.2f" %(x.total).to_f %></td>
			<% @total += (x.total).to_f#@total += (x.pedido_total_price).to_f %>
			<% @tempo = ((x.created_at + 1800)-(Time.now))/60 %>
			<% if @tempo>0 %>
				<% h= @tempo %>
			<% else %>
				<% h = 00 %>
			<% end %>
			<td align="center"><%= "00:%02d" %h %></td>
			<td align="center"><%= link_to ("X"),
                      apagarpedido_menucliente_path(x), 
                      :method => :delete,
                      :data => { :confirm => ('Deseja realmente deletar?')},
                      :class => 'btn btn-xs btn-danger' %></td>
			
		<% end %>
		</tr>
	</table>
	<p>
	<p>
	
	<center><body>Total dos pedidos <%= label_tag("R$ %.2f" %@total) %></body></center>
	<p>
	<p>
	
	<center><body>
	<%= link_to button_tag('Chamar Garçom'), chama_garcom2_menucliente_index_path, data: { confirm: "Esta ação solicitará a presença do garçom para cancelamento de pedidos. Tem certeza disso?"} %>
	<%= link_to button_tag('Novo Pedido'), pratoscar_menucliente_index_path %>
	<%= link_to button_tag('Voltar'), cardapio_menucliente_index_path %>
	</body></center>

app/views/menucliente/pratos.html.erb
<center>
<table>
<tr>
<td align="left"><font size="3"><%= render partial: "hora" %></font></td>
</tr>
</table>
</center>
<br>
<br>

<center>
<table>
<tr>
<td><body>Ordenar por:</body></td>
<td>
    <%= select_tag(:ordem, options_for_select([["Padrão","Padrao"],['MenorPreco',"Menor Preço"],['MaiorPreco',"Maior Preço"]])) %>
<br></td>
<td align="center"><%= link_to image_tag("icon_matriz.png", size: "32x32" ), pratoscar_menucliente_index_path  %></td>
</tr>
</center>
</table>
<p></p><br/><p></p>
<table align="center"border="3">
	<% @escolha_ped.each do |esc| %>
	<th width="10px"></th>
	<td>
		<center><%= link_to image_tag(esc.pictures[0], size: "200x200" ), menucliente_path(esc) %><br/><%= esc.name %><br/><%= "R$ %.2f" %esc.price %></center>
	</td>
	<th width="10px"></th>
	<% end %>
</table>
<br>
<center><%= link_to button_tag('Voltar'), cardapio_menucliente_index_path %></center>

app/views/menucliente/pratoscar.html.erb
<center>
<table>
<tr>
<td align="left"><font size="3"><%= render partial: "hora" %></font></td>
</tr>
</table>
</center>
<br>
<br>

<center>
<table>
<tr>
<td><body>Ordenar por:</body></td>
<td>
    <%= select_tag(:ordem, options_for_select([["Padrão","Padrao"],['MenorPreco',"Menor Preço"],['MaiorPreco',"Maior Preço"]])) %>
<br></td>
<td align="center"><%= link_to image_tag("icon_matriz1.png", size: "32x32" ), pratos_menucliente_index_path  %></td>
</tr>
</center>
</table>
<br>
<br>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% i=0 %>
    <% @escolha_ped.each do |esc| %>
        <% if i==0 %>
            <li data-target="#myCarousel" data-slide-to="<%= i %>" class="active"></li>
            <% i += 1 %>
        <% else %>
            <li data-target="#myCarousel" data-slide-to="<%= i %>"></li>
        <% end %>
	<% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    
    <% i=0 %>
    <% @escolha_ped.each do |esc| %>
        <% if i==0 %>
        <div class="item active">
            <% i += 1 %>
	      <center><%= link_to image_tag(esc.pictures[0], size: "300x200" ), menucliente_path(esc) %><br><br><%= esc.name %><br><%= "R$ %.2f" %esc.price %></center>
	    </div>
        <% else %>
	    <div class="item">
	      <center><%= link_to image_tag(esc.pictures[0], size: "300x200" ), menucliente_path(esc) %><br><br><%= esc.name %><br><%= "R$ %.2f" %esc.price %></center>
	    </div>
	    <% end %>
	<% end %>
    
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br>
<br>
<center><%= link_to t('.back', :default => t("helpers.links.back")), cardapio_menucliente_index_path, :class => 'btn btn-default' %></center>

app/views/menucliente/selecmesa.html.erb
<center>
<font size="3">
<% agora = Time.now %>
<%= (agora-10800).strftime("%d/%m/%y  %H:%M") %>
</font>
<br>
<br>
<%= form_tag (select_mesa_menucliente_index_path) do %>
    <br>
    <br>
    <body><font size="4">
        <%= select_tag('mesa', options_for_select([['Mesa 1',"Mesa 1"],['Mesa 2',"Mesa 2"],['Mesa 3',"Mesa 3"],['Mesa 4',"Mesa 4"],['Mesa 5',"Mesa 5"]]),{include_blank: true}) %>
    </font></body>
    <br>
    <br>
    <%= submit_tag "Escolher Mesa" %>
<% end %>
</center>
<br>
<br>
<center><%= link_to button_tag('Voltar'), home_menucliente_index_path %></center>

app/views/menucliente/show.html.erb
<%= form_tag (list_menucliente_path) do %>
    <center>
    <table>
    <tr>
    <td align="left"><font size="3"><%= render partial: "hora" %></font></td>
    </tr>
    </table>
    </center>
    <br>
    <br>

    <table border="2" align="center">
        <tr>
            <p>
        </tr>
        <tr>
            <td>
                <%= image_tag(@mostra.pictures[0], size: "200x200" ) %>
            </td>
            
    		<td>
    		    <center><body>Quantidade:
    		        <br><%= select_tag( 'qtds', options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9]])) %>
                </body></center>
                <br>
    		    <%= submit_tag "Add a lista" %>
    		</td>
    	</tr>
    </table>
<% end %>
    <br>
    <center><font size="5"><%= @mostra.name %></font>
    <br>
    <br><font size="4">Ingredientes:<%= @mostra.ingredient %></font></center>
    <br>
    <br>
    <center><%= link_to button_tag('Voltar'), pratoscar_menucliente_index_path %></center>