config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :manages
  
  
  resources :manages do
    resources :pictures, :only => [:create, :destroy] # support #create and #destroy
   
   
  end
  
   root 'menucliente#home'
   get "pedidosf" => "manages#pedidosf"
   get "solicitacoes" => "manages#solicitacoes"
   
   
  resources :menucliente do
    member do
      get "pratos"
      get "show"
      get "lista"
      post "lista"
      post "list"
      post "chama_garcom2"
      get "limplista"
      delete "del"=> "menucliente#destroy"
      post "pedid_save"
      delete "apagarpedido"=> "menucliente#apaga_ped"
      delete "apagarpedidof" => "menucliente#apaga_ped_f" 
      delete "apagarsolicitacoes" => "manages#sdestroy"
      get "atendersolic" => "manages#atendersolic"
    end
    
    collection do
      get "home"
      get "cardapio"
      get "pratos"
      get "show"
      get "lista"
      get "pedidos"
      post "pedidos"
      get "conta"
      get "pratoscar"
      post "chama_garcom"
      get "chama_garcom"
      get "chama_garcom2"
      get "chama_garcom3"
      get "selecmesa"
      post "select_mesa"
      
    end
  end
  
   

end

app/models/manage.rb
class Manage < ActiveRecord::Base
    mount_uploaders :pictures, PictureUploader
    validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
    validates :price, presence: true, length: { maximum: 10 }
    validates :ingredient, presence: true, length: { maximum: 200 }
    validates :pictures, presence: true
    
    
end

app/controllers/manages_controller.rb
class ManagesController < ApplicationController
  before_action :set_manage, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /manages
  # GET /manages.json
  def index
    @manages = Manage.all
  end

  # GET /manages/1
  # GET /manages/1.json
  def show
  end
   
  
  def solicitacoes
   @f_garcom = Chamagarcom.all
  end
  
  
  def atendersolic
    @soli = Chamagarcom.find(params[:id])
    @soli.status = 'Em Atendimento'
    @soli.save
    respond_to do |format|
      format.html { redirect_to solicitacoes_path, notice: 'Status modificado com sucesso.' }
      format.json { head :no_content }
    
    end
  end

 
  
  def sdestroy
    @soli = Chamagarcom.find(params[:id])
    @soli.destroy
    respond_to do |format|
      format.html { redirect_to solicitacoes_path, notice: 'Solicitação finalizada com sucesso.' }
      format.json { head :no_content }
    end
  end
    
    
  
  def pedidosf
    
  end

  # GET /manages/new
  def new
    @manage = Manage.new
  end

  # GET /manages/1/edit
  def edit
  end

  # POST /manages
  # POST /manages.json
  def create
    @manage = Manage.new(manage_params)

    respond_to do |format|
      if @manage.save
        format.html { redirect_to @manage, notice: 'Prato criado com sucesso.' }
        format.json { render :show, status: :created, location: @manage }
      else
        format.html { render :new }
        format.json { render json: @manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manages/1
  # PATCH/PUT /manages/1.json
  def update
    respond_to do |format|
      if @manage.update(manage_params)
        format.html { redirect_to @manage, notice: 'Prato atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @manage }
      else
        format.html { render :edit }
        format.json { render json: @manage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manages/1
  # DELETE /manages/1.json
  def destroy
    @manage.destroy
    respond_to do |format|
      format.html { redirect_to manages_url, notice: 'Prato deletado com sucesso.' }
      format.json { head :no_content }
    end
  end
  
 
  
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manage
      @manage = Manage.find(params[:id])
    end
    
   
    
    
    # Adicionar picture.
    def add_more_pictures(new_picture)
      pictures = @manage.pictures # copy the old pictures 
      pictures += new_pictures # concat old pictures with new ones
      @manage.pictures = pictures # assign back
    end
    
    
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def manage_params
      params.require(:manage).permit(:name, :price, :ingredient, {pictures: []})
    end
    
    
    
    
end

app/helpers/manages_helper.rb
module ManagesHelper
end

app/views/manages/_form.html.erb
<%= form_for @manage, :html => { :class => "form-horizontal manage", :multipart => true  } do |f| %>

  <% if @manage.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@manage.errors.count, "erro") %>:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @manage.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :ingredient, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ingredient, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ingredient) %>
  </div>
  
  
  <div class="form-group">
    <%= f.label 'Adicionar Imagens', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <br><%= f.file_field :pictures, multiple: true %> 
    </div>
    <%=f.error_span(:pictures) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                manages_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/manages/edit.html.erb
<%- model_class = Manage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>


<%= form_for @manage, :html => { :class => "form-horizontal manage", :multipart => true  } do |f| %>

  <% if @manage.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@manage.errors.count, "erro") %>:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @manage.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :ingredient, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ingredient, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ingredient) %>
  </div>
  
  
  <div class="form-group">
    <%= f.label 'Adicionar Imagens', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <br><%= f.file_field :pictures, multiple: true %> 
       <br><% @manage.pictures.each_with_index do |picture, index| %>
                <br><br>
                <%= image_tag(picture.url) %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      manage_picture_path(@manage,index),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
                <br><br>
            <% end %>
    </div>
    <%=f.error_span(:pictures) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                manages_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/manages/index.html.erb
<%- model_class = Manage -%>
<div class="page-header">
  <h1>Gerenciar Cardápio</h1>
</div>


  <div class="row">
  <div class="col-lg-3">
     <div class="well sidebar-nav">
            <h3>Menu</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Gerenciar Cardápio", manages_path  %></li>
              <li><%= link_to "Consultar Pedidos", pedidosf_path  %></li>
              <li><%= link_to "Contas", "/path3"  %></li>
              <li><%= link_to "Solicitações de Atendimento", solicitacoes_path  %></li>
            </ul>
          </div><!--/.well -->
        </div>
<div class="col-lg-9">
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_manage_path,
            :class => 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:ingredient) %></th>
      <th><%= model_class.human_attribute_name(:pictures) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @manages.each do |manage| %>
      <tr>
        <td><%= link_to manage.id, manage_path(manage) %></td>
        <td><%= manage.name %></td>
        <td><%= manage.price %></td>
        <td><%= manage.ingredient %></td>
        <td><% manage.pictures.each do |p| %>
                <%= image_tag p.url(:thumb) %>
                <br>
                <br>
            <% end %>
        </td>
         
        <td><%=l manage.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_manage_path(manage), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      manage_path(manage),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>




</div>

</div>

app/views/manages/new.html.erb
<%- model_class = Manage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/manages/pedidosf.html.erb
<div class="page-header">
  <h1>Visualizar Pedidos</h1>
</div>


  <div class="row">
  <div class="col-lg-3">
     <div class="well sidebar-nav">
            <h3>Menu</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Gerenciar Cardápio", manages_path  %></li>
              <li><%= link_to "Consultar Pedidos", pedidosf_path  %></li>
              <li><%= link_to "Contas", "/path3"  %></li>
              <li><%= link_to "Solicitações de Atendimento", solicitacoes_path  %></li>
            </ul>
          </div><!--/.well -->
        </div>
<div class="col-lg-9">
<table class="table table-striped">
  <thead>
    <tr>
      <th><center>Mesa</center></th>
      <th><center>Código</center></th>
      <th><center>Item</center></th>
      <th><center>Quantidade</center></th>
      <th><center>Tempo Estimado</center></th>
      <th><center><%=t '.actions', :default => t("helpers.actions") %></center></th>
    </tr>
  </thead>
  <tbody>
    <% @pedidosf = OrderListDef.all %>
    <% @pedidosf.each do |x| %>
      <tr>
        <td align="center"><%= x.mesa_n %></td>
        <td align="center"><%= x.n_order %></td>
        <td align="center"><%=x.namep %> </td>
        <td align="center"><%=x.qtd %></td>
       	<% @tempo = ((x.created_at + 1800)-(Time.now))/60 %>
			<% if @tempo>0 %>
				<% h= @tempo %>
			<% else %>
				<% h = 00 %>
			<% end %>
			<td><%= "00:%02d" %h %></td>
        <td><%= link_to "Finalizar",
                      apagarpedidof_menucliente_path(x), 
                      :method => :delete,
                      :data => { :confirm => ('Deseja realmente finalizar este pedido?')},
                      :class => 'btn btn-xs btn-danger' %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>




</div>

</div>

app/views/manages/show.html.erb
<%- model_class = Manage -%>
<div class="page-header">
  <h1><%= @manage.name %></h1>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              manages_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_manage_path(@manage), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              manage_path(@manage),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
 <br><br>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @manage.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @manage.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ingredient) %>:</strong></dt>
  <dd><%= @manage.ingredient %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pictures) %>:</strong></dt>
  <dd> <% @manage.pictures.each do |p| %>
                <br><br>
                <%= image_tag p %>
                <br><br>
            <% end %>
        </dd>
</dl>

app/views/manages/solicitacoes.erb
<div class="page-header">
  <h1>Visualizar Pedidos</h1>
</div>


  <div class="row">
  <div class="col-lg-3">
     <div class="well sidebar-nav">
            <h3>Menu</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Gerenciar Cardápio", manages_path  %></li>
              <li><%= link_to "Consultar Pedidos", pedidosf_path  %></li>
              <li><%= link_to "Contas", "/path3"  %></li>
              <li><%= link_to "Solicitações de Atendimento", solicitacoes_path  %></li>
            </ul>
          </div><!--/.well -->
        </div>
<div class="col-lg-9">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Mesa</th>
      <th>Solicitação</th>
      <th>Status</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @f_garcom.each do |x| %>
      <tr>
        <td><%= x.mesa_num %></td>
        <td><%= "Dúvidas" if x.cod_chamado == 01%>
        <%= "Cancelamento de Pedido" if x.cod_chamado == 02%>
        <%= "Pagamento" if x.cod_chamado == 03%></td>
        <td><%= x.status %></td>
         <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      solicitacoes_path(x), :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Atendido(Limpar)',
                      solicitacoes_path(x),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>




</div>

</div>

app/views/manages/solicitacoes.html.erb
<div class="page-header">
  <h1>Solicitações de Atendimento</h1>
</div>


  <div class="row">
  <div class="col-lg-3">
     <div class="well sidebar-nav">
            <h3>Menu</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Gerenciar Cardápio", manages_path  %></li>
              <li><%= link_to "Consultar Pedidos", pedidosf_path  %></li>
              <li><%= link_to "Contas", "/path3"  %></li>
              <li><%= link_to "Solicitações de Atendimento", solicitacoes_path  %></li>
            </ul>
          </div><!--/.well -->
        </div>
<div class="col-lg-9">
<table class="table table-striped">
  <thead>
    <tr>
      <th><center>Mesa</center></th>
      <th><center>Solicitação</center></th>
      <th><center>Status</center></th>
      <th><center><%=t '.actions', :default => t("helpers.actions") %></center></th>
    </tr>
  </thead>
  <tbody>
    <% @f_garcom.each do |x| %>
      <tr>
        <td align="center"><%= x.mesa_num %></td>
        <td align="center"><%= "Dúvidas" if x.cod_chamado == 01%>
        <%= "Cancelamento de Pedido" if x.cod_chamado == 02%>
        <%= "Pagamento" if x.cod_chamado == 03%></td>
        <td align="center"><%= x.status %></td>
         <td align="center">
          <%= link_to 'Atender',
                      atendersolic_menucliente_path(x), :data => { :confirm => 'Esta ação modificará o status da solicitação para "Em Atendimento". Tem certeza disso?' }, :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Finalizar',
                      apagarsolicitacoes_menucliente_path(x),
                      :method => :delete,
                      :data => { :confirm => 'Esta ação removerá a solicitação da lista. Tem certeza disso?' },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>




</div>

</div>